apiVersion: apps/v1
kind: Deployment
metadata:
  name: skodb-deployment
  labels:
    app: skotemp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skotemp
  template:
    metadata:
      labels:
        app: skotemp
    spec:
      containers:
        - name: skodb
          image: us.gcr.io/fred-hsu-veos/skodb:0.1
          imagePullPolicy: Always
          ports:
          - containerPort: 5002
          command: [ "python", "src/app.py" ]
          env:
            - name: MONGO_HOST
              value: "10.90.224.138"
        - name: skotemp
          image: us.gcr.io/fred-hsu-veos/skotemp:0.1
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
          command: [ "python", "src/app.py" ]
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

---
kind: Service
apiVersion: v1
metadata:
  name: skotemp-svc
spec:
  selector:
    app: skotemp
  ports:
  - protocol: TCP
    port: 5000 # port to expose within cluster
    targetPort: 5000 # port that pod/container listens to
    nodePort: 31514 # mapping to nodeport
  type: NodePort